# Generated by Django 4.0.6 on 2022-07-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='UTF',
            new_name='UTC',
        ),
    ]
