# Generated by Django 4.0.6 on 2022-07-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_rename_utf_city_utc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
